NotEduWeb/NotEduWeb/Models/Notes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotEduWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Notes
    {
        [DisplayName("Valeur")]
        [Required]
        [Range(0.00, 20.00, ErrorMessage = "La valeur doit être comprise entre 0.00 et 20.00.")]
        public decimal valeur { get; set; }
        [DisplayName("Appréciation")]
        public string appreciation { get; set; }
        [DisplayName("Elève")]
        [Required]
        public int fk_note_eleve { get; set; }
        [DisplayName("Cours")]
        [Required]
        public int fk_note_cours { get; set; }

        public virtual Cours Cours { get; set; }
        public virtual Eleves Eleves { get; set; }
    }
}

NotEduWeb/NotEduWeb/Controllers/ElevesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NotEduWeb.Models;
using NotEduWeb.Tools;

namespace NotEduWeb.Controllers
{
    public class ElevesController : Controller
    {
        private NotEduWebEntities db = new NotEduWebEntities();

        // GET: Eleves
        public ActionResult Index()
        {
            var eleves = db.Eleves.Include(e => e.Promotions).OrderBy(e => e.nom);
            return View(eleves.ToList());
        }

        // GET: Eleves/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eleves eleves = db.Eleves.Find(id);
            if (eleves == null)
            {
                return HttpNotFound();
            }
            IEnumerable<Notes> notesEleve = from note in db.Notes
                                             join cours in db.Cours
                                             on note.fk_note_cours equals cours.ID_cours
                                             where note.fk_note_eleve == id
                                             select note;
            List<decimal> notesValeurs = notesEleve.Select(note => note.valeur).ToList();
            if(notesValeurs.Count > 0)
            {
                ViewBag.moyenne = Utilities.ArrondirNote(decimal.ToDouble(notesValeurs.Average()));

            } else
            {
                ViewBag.moyenne = -1;
            }

            ViewBag.listeNotes = notesEleve.OrderBy(n => n.Cours.nom).ToList();
            return View(eleves);
        }

        // GET: Eleves/Create
        public ActionResult Create()
        {
            ViewBag.fk_eleve_promotion = new SelectList(db.Promotions, "ID_promotion", "nom");
            Dictionary<int, string> dicoPromos = DbTools.GetListeDesPromotionsFormattee();

            ViewBag.promos = dicoPromos;
            return View();
        }

        // POST: Eleves/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_eleve,nom,prenom,date_naissance,fk_eleve_promotion")] Eleves eleves)
        {
            if (ModelState.IsValid)
            {
                db.Eleves.Add(eleves);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.fk_eleve_promotion = new SelectList(db.Promotions, "ID_promotion", "nom", eleves.fk_eleve_promotion);
            Dictionary<int, string> dicoPromos = DbTools.GetListeDesPromotionsFormattee();

            ViewBag.promos = dicoPromos;
            return View(eleves);
        }

        // GET: Eleves/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eleves eleves = db.Eleves.Find(id);
            if (eleves == null)
            {
                return HttpNotFound();
            }
            ViewBag.date = eleves.date_naissance.ToString("yyyy-MM-dd");
            ViewBag.fk_eleve_promotion = new SelectList(db.Promotions, "ID_promotion", "nom", eleves.fk_eleve_promotion);
            Dictionary<int, string> dicoPromos = DbTools.GetListeDesPromotionsFormattee();
            ViewBag.promos = dicoPromos;
            return View(eleves);
        }

        // POST: Eleves/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_eleve,nom,prenom,date_naissance,fk_eleve_promotion")] Eleves eleves)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eleves).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.fk_eleve_promotion = new SelectList(db.Promotions, "ID_promotion", "nom", eleves.fk_eleve_promotion);
            return View(eleves);
        }

        // GET: Eleves/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eleves eleves = db.Eleves.Find(id);
            if (eleves == null)
            {
                return HttpNotFound();
            }
            return View(eleves);
        }

        // POST: Eleves/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Eleves eleves = db.Eleves.Find(id);
            db.Eleves.Remove(eleves);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NotEduWeb/NotEduWeb/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NotEduWeb.Models;
using NotEduWeb.Tools;

namespace NotEduWeb.Controllers
{
    public class NotesController : Controller
    {
        private NotEduWebEntities db = new NotEduWebEntities();

        // GET: Notes
        public ActionResult Index()
        {
            var notes = db.Notes.Include(n => n.Cours).Include(n => n.Eleves);
            return View(notes.ToList());
        }

        // GET: Notes/Details/5
        public ActionResult Details(int? idEleve, int? idCours)
        {
            if (idEleve == null || idCours == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Notes notes = db.Notes.Find(idEleve, idCours);
            if (notes == null)
            {
                return HttpNotFound();
            }
            return View(notes);
        }

        // GET: Notes/Create
        public ActionResult Create()
        {
            ViewBag.fk_note_cours = new SelectList(db.Cours, "ID_cours", "nom");
            ViewBag.fk_note_eleve = new SelectList(db.Eleves, "ID_eleve", "nom");
            Dictionary<int, string> dicoEleves = DbTools.GetListeDesElevesFormattee();

            ViewBag.eleves = dicoEleves;
            return View();
        }

        // POST: Notes/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "valeur,appreciation,fk_note_eleve,fk_note_cours")] Notes notes)
        {
            if (ModelState.IsValid)
            {
                Notes existingNote = db.Notes.Find(notes.fk_note_eleve, notes.fk_note_cours);
                if(existingNote != null)
                {
                    ViewBag.Error = "Cet élève possède déjà une note pour cette matière.";
                    Dictionary<int, string> dicoEleves = DbTools.GetListeDesElevesFormattee();
                    ViewBag.eleves = dicoEleves;
                    ViewBag.fk_note_cours = new SelectList(db.Cours, "ID_cours", "nom");
                    ViewBag.fk_note_eleve = new SelectList(db.Eleves, "ID_eleve", "nom");
                    return View("Create");
                }
                db.Notes.Add(notes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            Dictionary<int, string> dicoElevesElse = DbTools.GetListeDesElevesFormattee();

            ViewBag.eleves = dicoElevesElse;
            ViewBag.fk_note_cours = new SelectList(db.Cours, "ID_cours", "nom", notes.fk_note_cours);
            ViewBag.fk_note_eleve = new SelectList(db.Eleves, "ID_eleve", "nom", notes.fk_note_eleve);
            return View(notes);
        }

        // GET: Notes/Edit/5
        public ActionResult Edit(int? idEleve, int? idCours)
        {
            if (idEleve == null || idCours == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Notes notes = db.Notes.Find(idEleve, idCours);
            if (notes == null)
            {
                return HttpNotFound();
            }
            ViewBag.fk_note_cours = new SelectList(db.Cours, "ID_cours", "nom", notes.fk_note_cours);
            ViewBag.fk_note_eleve = new SelectList(db.Eleves, "ID_eleve", "nom", notes.fk_note_eleve);

            Dictionary<int, string> dicoEleves = DbTools.GetListeDesElevesFormattee();
            ViewBag.eleves = dicoEleves;
            return View(notes);
        }

        // POST: Notes/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "valeur,appreciation,fk_note_eleve,fk_note_cours")] Notes notes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(notes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.fk_note_cours = new SelectList(db.Cours, "ID_cours", "nom", notes.fk_note_cours);
            ViewBag.fk_note_eleve = new SelectList(db.Eleves, "ID_eleve", "nom", notes.fk_note_eleve);
            return View(notes);
        }

        // GET: Notes/Delete/5
        public ActionResult Delete(int? idEleve, int? idCours)
        {
            if (idEleve == null || idCours == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Notes notes = db.Notes.Find(idEleve, idCours);
            if (notes == null)
            {
                return HttpNotFound();
            }
            return View(notes);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? idEleve, int? idCours)
        {
            Notes notes = db.Notes.Find(idEleve, idCours);
            db.Notes.Remove(notes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NotEduWeb/NotEduWeb/Views/Notes/Create.cshtml
@model NotEduWeb.Models.Notes

@{
    ViewBag.Title = "Créer une note";
}

<div class="createpage">
    <h2>Créer une note</h2>

    <div class="box">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="edit-form">

            @Html.ValidationSummary(true, "", new { @class = "error" })
            <div class="form-group">
                @Html.LabelFor(model => model.valeur, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.valeur, new { htmlAttributes = new { @class = "form-control" } })
                <p class="error">
                    @Html.ValidationMessageFor(model => model.valeur, "", new { @class = "error" })
                </p>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.appreciation, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.appreciation, new { htmlAttributes = new { @class = "form-control" } })
                <p class="error">
                    @Html.ValidationMessageFor(model => model.appreciation, "", new { @class = "error" })
                </p>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fk_note_eleve, "Elève", htmlAttributes: new { @class = "control-label col-md-2" })
                <select class="form-control" id="fk_note_eleve" name="fk_note_eleve">
                    @if (ViewBag.eleves.Count > 0)
                    {
                        foreach (var item in ViewBag.eleves)
                        {
                            <option value="@item.Key">@item.Value</option>
                        }

                    }
                    else
                    {
                        <option value=""></option>
                        @Html.ActionLink("Créer un élève", "Create", "Eleves")
                    }
                </select>
                <p class="error">
                    @Html.ValidationMessageFor(model => model.fk_note_eleve, "", new { @class = "error" })
                </p>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fk_note_cours, "Cours", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownList("fk_note_cours", null, htmlAttributes: new { @class = "form-control" })
                <p class="error">
                    @Html.ValidationMessageFor(model => model.fk_note_cours, "", new { @class = "error" })
                </p>
            </div>

            <p class="error">@ViewBag.Error</p>

            <div class="editpage-buttons">
                <a class="btn btn-transparent" href="@Url.Action("Index")">Retour à la liste</a>
                <input type="submit" value="Créer" class="btn btn-secondary" />
            </div>
        </div>
        }
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
    </div>

NotEduWeb/NotEduWeb/Views/Notes/Delete.cshtml
@model NotEduWeb.Models.Notes
@using NotEduWeb.Tools
@{
    ViewBag.Title = "Delete";
}

<div class="deletepage">
    <h2>Suppression d'une note</h2>
    <div class="box">
        <h3>Etes-vous sûr de vouloir supprimer ceci ?</h3>
        <div class="delete-item">
            <p><span class="item-title">@Html.DisplayNameFor(model => model.valeur) :</span> @Html.DisplayFor(model => model.valeur) / 20</p>
            <p>
                <span class="item-title">
                    @Html.DisplayNameFor(model => model.appreciation) :
                </span>  @Html.DisplayFor(model => model.appreciation)
            </p>
            <p>
                <span class="item-title">
                    @Html.DisplayNameFor(model => model.Cours.nom) :
                </span>  @Html.DisplayFor(model => model.Cours.nom)
            </p>
            <p>
                <span class="item-title">
                    @Html.DisplayNameFor(model => model.Eleves.nom) :
                </span>  @Html.ActionLink(Utilities.GetNomCompletUser(Model.Eleves), "Details", "Eleves", new { id = Model.fk_note_eleve }, new { @class = "user-link" })

            </p>
            <p>
                <span class="item-title">Promotion :</span>  @Model.Eleves.Promotions.annee - @Model.Eleves.Promotions.nom
            </p>
        </div>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="editpage-buttons">
                    <a class="btn btn-transparent" href="@Url.Action("Index")">Retour à la liste</a>
                    <input type="submit" value="Supprimer" class="btn btn-warning" />
                </div>
            }
        </div>
    </div>

NotEduWeb/NotEduWeb/Views/Notes/Details.cshtml
@model NotEduWeb.Models.Notes
@using NotEduWeb.Tools
@{
    ViewBag.Title = "Détails";
}

<div class="detailspage">
    <h2>Détails de la note</h2>

    <div class="box">
        <p>
            <span class="item-title">@Html.DisplayNameFor(model => model.valeur) :</span>
            @Html.DisplayFor(model => model.valeur) / 20
        </p>
        <p>
            <span class="item-title">@Html.DisplayNameFor(model => model.appreciation) :</span>
            @Html.DisplayFor(model => model.appreciation)
        </p>
        <p>
            <span class="item-title">@Html.DisplayNameFor(model => model.Cours.nom) :</span>
            @Html.DisplayFor(model => model.Cours.nom)
        </p>
        <p>
            <span class="item-title">@Html.DisplayNameFor(model => model.Eleves.nom) :</span>
            @Html.ActionLink(Utilities.GetNomCompletUser(Model.Eleves), "Details", "Eleves", new { id = Model.fk_note_eleve }, new { @class = "user-link" })
        </p>
        <p>
            <span class="item-title">Promotion :</span>
            @Model.Eleves.Promotions.annee - @Model.Eleves.Promotions.nom
        </p>
        <div class="editpage-buttons">
            <a class="btn btn-transparent" href="@Url.Action("Index")">Retour à la liste</a>
            <a href="@Url.Action("Edit", "Notes", new { idEleve = Model.fk_note_eleve, idCours = Model.fk_note_cours })" class="btn btn-secondary">Editer</a>
        </div>
    </div>    
</div>

NotEduWeb/NotEduWeb/Views/Notes/Edit.cshtml
@model NotEduWeb.Models.Notes

@{
    ViewBag.Title = "Editer une note";
}

<div class="editpage">
    <h2>Edition d'une note</h2>
    <div class="box">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="edit-form">

                @Html.ValidationSummary(true, "", new { @class = "error" })
                <div class="form-group">
                    @Html.LabelFor(model => model.valeur, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.valeur, new { htmlAttributes = new { @class = "form-control" } })
                    <p class="error">
                        @Html.ValidationMessageFor(model => model.valeur, "", new { @class = "error" })
                    </p>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.appreciation, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.appreciation, new { htmlAttributes = new { @class = "form-control" } })
                    <p class="error">
                        @Html.ValidationMessageFor(model => model.appreciation, "", new { @class = "error" })
                    </p>
                </div>

                @Html.HiddenFor(model => model.fk_note_eleve)

                @Html.HiddenFor(model => model.fk_note_cours)

                <div class="editpage-buttons">
                    <a class="btn btn-transparent" href="@Url.Action("Index")">Retour à la liste</a>
                    <a class="btn btn-warning" href="@Url.Action("Delete", "Notes", new { idEleve = Model.fk_note_eleve, idCours = Model.fk_note_cours })">Supprimer</a>
                    <input type="submit" value="Mettre à jour" class="btn btn-secondary" />
                </div>

            </div>
        }
    </div>
        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
    </div>

NotEduWeb/NotEduWeb/Views/Notes/Index.cshtml
@model IEnumerable<NotEduWeb.Models.Notes>
@using NotEduWeb.Tools

@{
    ViewBag.Title = "Liste des notes";
}


<div class="listpage notespage">
    <h2>Liste des notes</h2>

    <a href="@Url.Action("Create","Notes")" class="btn btn-primary">
        <ion-icon name="add-circle"></ion-icon>
        Créer une note
    </a>

    @foreach (var item in Model)
    {
        <div class="listpage-item box">

            <div class="listpage-item-first">
                <span class="note-eleve">@Html.DisplayFor(modelItem => item.valeur) / 20</span> en @Html.DisplayFor(modelItem => item.Cours.nom)
            </div>

            <div class="listpage-item-second appreciation">
                @if(item.appreciation != null)
                {
                    <p class="appreciation-text">" @Html.DisplayFor(modelItem => item.appreciation) "</p>
                } else
                {
                    <p class="appreciation-text appreciation-vide">(Aucune appréciation saisie)</p>
                }
            </div>

            <div class="listpage-item-second">
                Pour l'élève :
                <a href="@Url.Action("Details", "Eleves", new { id = item.fk_note_eleve })" class="user-link">@Utilities.GetNomCompletUser(item.Eleves)</a>
                </div>
            <div class="listpage-item-buttons">
                <a href="@Url.Action("Edit","Notes",new { idEleve = item.fk_note_eleve, idCours = item.fk_note_cours })" class="btn btn-secondary">
                    Editer
                </a>
                <a href="@Url.Action("Details","Notes",new { idEleve = item.fk_note_eleve, idCours = item.fk_note_cours })" class="btn btn-secondary">
                    Détails
                </a>
                <a href="@Url.Action("Delete","Notes",new { idEleve = item.fk_note_eleve, idCours = item.fk_note_cours })" class="btn btn-warning">
                    Supprimer
                </a>
            </div>
        </div>
    }

</div>