NotEduWeb/NotEduWeb/Models/Promotions.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotEduWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Promotions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotions()
        {
            this.Eleves = new HashSet<Eleves>();
        }
    
        public int ID_promotion { get; set; }
        [DisplayName("Année")]
        [Required]
        [Range(1950, 2100, ErrorMessage = "La valeur doit être comprise entre 1950 et 2100.")]
        public int annee { get; set; }
        [Required]
        [DisplayName("Nom promotion")]
        public string nom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eleves> Eleves { get; set; }
    }
}

NotEduWeb/NotEduWeb/Controllers/CoursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NotEduWeb.Models;
using NotEduWeb.Tools;

namespace NotEduWeb.Controllers
{
    public class CoursController : Controller
    {
        private NotEduWebEntities db = new NotEduWebEntities();

        // GET: Cours
        public ActionResult Index()
        {
            return View(db.Cours.OrderBy(c => c.nom).ToList());
        }

        // GET: Cours/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Cours.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }

            List<MoyenneParCours> itemDuCours = DbTools.FetchMoyenneCoursPromo().Where(item => item.CoursID == id).OrderByDescending(i => i.Annee).ToList();
            ViewBag.MoyennesPromos = itemDuCours;
            return View(cours);
        }

        // GET: Cours/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cours/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_cours,nom")] Cours cours)
        {
            if (ModelState.IsValid)
            {
                Cours coursExistant = db.Cours.Where(c => c.nom.ToLower().Trim() == cours.nom.ToLower().Trim()).FirstOrDefault();
                if(coursExistant != null)
                {
                    ViewBag.Error = "Un cours avec ce nom existe déjà.";
                    return View("Create");
                }
                db.Cours.Add(cours);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cours);
        }

        // GET: Cours/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Cours.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }

        // POST: Cours/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_cours,nom")] Cours cours)
        {
            if (ModelState.IsValid)
            {
                Cours coursExistant = db.Cours.Where(c => c.nom.ToLower().Trim() == cours.nom.ToLower().Trim()).FirstOrDefault();
                if (coursExistant != null)
                {
                    ViewBag.Error = "Un cours avec ce nom existe déjà.";
                    return View("Edit");
                }
                db.Entry(cours).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cours);
        }

        // GET: Cours/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Cours.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }

        // POST: Cours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cours cours = db.Cours.Find(id);
            db.Cours.Remove(cours);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NotEduWeb/NotEduWeb/Controllers/ElevesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NotEduWeb.Models;
using NotEduWeb.Tools;

namespace NotEduWeb.Controllers
{
    public class ElevesController : Controller
    {
        private NotEduWebEntities db = new NotEduWebEntities();

        // GET: Eleves
        public ActionResult Index()
        {
            var eleves = db.Eleves.Include(e => e.Promotions).OrderBy(e => e.nom);
            return View(eleves.ToList());
        }

        // GET: Eleves/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eleves eleves = db.Eleves.Find(id);
            if (eleves == null)
            {
                return HttpNotFound();
            }
            IEnumerable<Notes> notesEleve = from note in db.Notes
                                             join cours in db.Cours
                                             on note.fk_note_cours equals cours.ID_cours
                                             where note.fk_note_eleve == id
                                             select note;
            List<decimal> notesValeurs = notesEleve.Select(note => note.valeur).ToList();
            if(notesValeurs.Count > 0)
            {
                ViewBag.moyenne = Utilities.ArrondirNote(decimal.ToDouble(notesValeurs.Average()));

            } else
            {
                ViewBag.moyenne = -1;
            }

            ViewBag.listeNotes = notesEleve.OrderBy(n => n.Cours.nom).ToList();
            return View(eleves);
        }

        // GET: Eleves/Create
        public ActionResult Create()
        {
            ViewBag.fk_eleve_promotion = new SelectList(db.Promotions, "ID_promotion", "nom");
            Dictionary<int, string> dicoPromos = DbTools.GetListeDesPromotionsFormattee();

            ViewBag.promos = dicoPromos;
            return View();
        }

        // POST: Eleves/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_eleve,nom,prenom,date_naissance,fk_eleve_promotion")] Eleves eleves)
        {
            if (ModelState.IsValid)
            {
                db.Eleves.Add(eleves);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.fk_eleve_promotion = new SelectList(db.Promotions, "ID_promotion", "nom", eleves.fk_eleve_promotion);
            Dictionary<int, string> dicoPromos = DbTools.GetListeDesPromotionsFormattee();

            ViewBag.promos = dicoPromos;
            return View(eleves);
        }

        // GET: Eleves/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eleves eleves = db.Eleves.Find(id);
            if (eleves == null)
            {
                return HttpNotFound();
            }
            ViewBag.date = eleves.date_naissance.ToString("yyyy-MM-dd");
            ViewBag.fk_eleve_promotion = new SelectList(db.Promotions, "ID_promotion", "nom", eleves.fk_eleve_promotion);
            Dictionary<int, string> dicoPromos = DbTools.GetListeDesPromotionsFormattee();
            ViewBag.promos = dicoPromos;
            return View(eleves);
        }

        // POST: Eleves/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_eleve,nom,prenom,date_naissance,fk_eleve_promotion")] Eleves eleves)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eleves).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.fk_eleve_promotion = new SelectList(db.Promotions, "ID_promotion", "nom", eleves.fk_eleve_promotion);
            return View(eleves);
        }

        // GET: Eleves/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eleves eleves = db.Eleves.Find(id);
            if (eleves == null)
            {
                return HttpNotFound();
            }
            return View(eleves);
        }

        // POST: Eleves/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Eleves eleves = db.Eleves.Find(id);
            db.Eleves.Remove(eleves);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NotEduWeb/NotEduWeb/Controllers/PromotionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NotEduWeb.Models;
using NotEduWeb.Tools;

namespace NotEduWeb.Controllers
{
    public class PromotionsController : Controller
    {
        private NotEduWebEntities db = new NotEduWebEntities();

        // GET: Promotions
        public ActionResult Index()
        {
            return View(db.Promotions.OrderBy(p => p.annee).ToList());
        }

        // GET: Promotions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promotions promotions = db.Promotions.Find(id);
            if (promotions == null)
            {
                return HttpNotFound();
            }
            IEnumerable<Eleves> elevesPromo = from eleve in db.Eleves
                                              where eleve.fk_eleve_promotion == id
                                              select eleve;
            ViewBag.ElevesPromo = elevesPromo.OrderBy(e => e.nom).ToList();
            List<MoyenneParCours> itemDeLaPromo = DbTools.FetchMoyenneCoursPromo().Where(item => item.PromotionID == id).OrderBy(i => i.Cours).ToList();
            ViewBag.MoyennesPromos = itemDeLaPromo;
            return View(promotions);
        }

        // GET: Promotions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Promotions/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_promotion,annee,nom")] Promotions promotions)
        {
            if (ModelState.IsValid)
            {
                db.Promotions.Add(promotions);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(promotions);
        }

        // GET: Promotions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promotions promotions = db.Promotions.Find(id);
            if (promotions == null)
            {
                return HttpNotFound();
            }
            return View(promotions);
        }

        // POST: Promotions/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_promotion,annee,nom")] Promotions promotions)
        {
            if (ModelState.IsValid)
            {
                db.Entry(promotions).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(promotions);
        }

        // GET: Promotions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promotions promotions = db.Promotions.Find(id);
            if (promotions == null)
            {
                return HttpNotFound();
            }
            return View(promotions);
        }

        // POST: Promotions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Promotions promotions = db.Promotions.Find(id);
            db.Promotions.Remove(promotions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NotEduWeb/NotEduWeb/Views/Promotions/Create.cshtml
@model NotEduWeb.Models.Promotions

@{
    ViewBag.Title = "Créer une promotion";
}

<div class="createpage">
    <h2>Créer une promotion</h2>

    <div class="box">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="edit-form">

                @Html.ValidationSummary(true, "", new { @class = "error" })
                <div class="form-group">
                    @Html.LabelFor(model => model.annee, htmlAttributes: new { @class = "control-label col-md-2" })
                    <input type="number" step="1" class="form-control" data-val="true" data-val-number="Le champ Année doit être un nombre." data-val-required="Le champ Année est requis." id="annee" name="annee" value="" />
                    <p class="error">
                        @Html.ValidationMessageFor(model => model.annee, "", new { @class = "error" })
                    </p>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                    <p class="error">
                        @Html.ValidationMessageFor(model => model.nom, "", new { @class = "error" })
                    </p>
                </div>

                <div class="editpage-buttons">
                    <a class="btn btn-transparent" href="@Url.Action("Index")">Retour à la liste</a>
                    <input type="submit" value="Créer" class="btn btn-secondary" />
                </div>
            </div>
        }
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
    </div>

NotEduWeb/NotEduWeb/Views/Promotions/Delete.cshtml
@model NotEduWeb.Models.Promotions

@{
    ViewBag.Title = "Supprimer une promotion";
}

<div class="deletepage">
    <h2>Suppression d'une promotion</h2>

    <div class="box">
        <h3>Etes-vous sûr de vouloir supprimer ceci ?</h3>

        <p><span class="item-title">@Html.DisplayNameFor(model => model.annee) :</span> @Html.DisplayFor(model => model.annee)</p>
        <p><span class="item-title">@Html.DisplayNameFor(model => model.nom) :</span> @Html.DisplayFor(model => model.nom)</p>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="editpage-buttons">
                <a class="btn btn-transparent" href="@Url.Action("Index")">Retour à la liste</a>
                <input type="submit" value="Supprimer" class="btn btn-warning" />
            </div>
        }
    </div>
    </div>

NotEduWeb/NotEduWeb/Views/Promotions/Details.cshtml
@model NotEduWeb.Models.Promotions
@using NotEduWeb.Tools
@{
    ViewBag.Title = "Détails";
}

<div class="detailspage">
    <h2>Détails de la promotion</h2>

    <div class="box">
        <p>
            <span class="item-title">@Html.DisplayNameFor(model => model.annee) :</span>
            @Html.DisplayFor(model => model.annee)
        </p>

        <p>
            <span class="item-title">@Html.DisplayNameFor(model => model.nom) :</span>
            @Html.DisplayFor(model => model.nom)
        </p>
        <div class="editpage-buttons">
            <a class="btn btn-transparent" href="@Url.Action("Index")">Retour à la liste</a>
            <a href="@Url.Action("Edit", "Promotions", new { id = Model.ID_promotion })" class="btn btn-secondary">Editer</a>
        </div>
    </div>

    <div class="box">
        <h3>Moyennes des cours de la promotion</h3>
        @if (ViewBag.MoyennesPromos.Count > 0)
        {
            foreach (var item in ViewBag.MoyennesPromos)
            {
                <div class="moyenne-promo">
                    <a href="@Url.Action("Details", "Cours", new { id = item.CoursID })">@item.Cours</a>
                    <div>@string.Format("{0:N2}", item.Moyenne) / 20</div>
                </div>
            }
        }
        else
        {
            <p>Aucune donnée à afficher pour le moment.</p>
        }
    </div>

    <div class="box liste-eleves-promo">
        <h3>Elèves de la promotion</h3>
        @if (ViewBag.ElevesPromo.Count > 0)
        {
            <ul>
                @foreach (var eleve in ViewBag.ElevesPromo)
                {
                    string name = Utilities.GetNomCompletUser(eleve);
                    <li>
                        @Html.ActionLink(name, "Details", "Eleves", new { id = eleve.ID_eleve }, new { @class = "user-link" }), né(e) le @Utilities.ConvertInShortDate(eleve.date_naissance)
                    </li>
                }
            </ul>

        }
        else
        {
            <p>Aucun élève pour le moment.</p>
        }
    </div>
</div>

NotEduWeb/NotEduWeb/Views/Promotions/Edit.cshtml
@model NotEduWeb.Models.Promotions

@{
    ViewBag.Title = "Editer une promotion";
}

<div class="editpage">
    <h2>Edition d'une promotion</h2>


<div class="box">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


    <div class="edit-form">
        @Html.ValidationSummary(true, "", new { @class = "error" })
        @Html.HiddenFor(model => model.ID_promotion)

        <div class="form-group">
            @Html.LabelFor(model => model.annee, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.annee, new { htmlAttributes = new { @class = "form-control" } })
            <p class="error">
                @Html.ValidationMessageFor(model => model.annee, "", new { @class = "error" })
            </p>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
            <p class="error">
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "error" })
            </p>
        </div>

        <div class="editpage-buttons">
            <a class="btn btn-transparent" href="@Url.Action("Index")">Retour à la liste</a>
            <input type="submit" value="Mettre à jour" class="btn btn-secondary" />
        </div>
    </div>
      }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
</div>

NotEduWeb/NotEduWeb/Views/Promotions/Index.cshtml
@model IEnumerable<NotEduWeb.Models.Promotions>

@{
    ViewBag.Title = "Liste des promotions";
}

<div class="listpage promopage">
    <h2>Liste des promotions</h2>

    <a href="@Url.Action("Create","Promotions")" class="btn btn-primary">
        <ion-icon name="add-circle"></ion-icon>
        Créer une promotion
    </a>
    @foreach (var item in Model)
    {
        <div class="listpage-item box">
            <div class="listpage-item-first">
                @Html.DisplayFor(modelItem => item.annee) - @Html.DisplayFor(modelItem => item.nom)
            </div>
            <div class="listpage-item-buttons">
                <a href="@Url.Action("Edit","Promotions",new { id = item.ID_promotion })" class="btn btn-secondary">
                    Editer
                </a>
                <a href="@Url.Action("Details","Promotions",new { id = item.ID_promotion })" class="btn btn-secondary">
                    Détails
                </a>
                <a href="@Url.Action("Delete","Promotions",new { id = item.ID_promotion })" class="btn btn-warning">
                    Supprimer
                </a>
            </div>
        </div>
    }

</div>